### ISSUE TITLE
Increase default horizontal/vertical viewing angle in attention/deixis visualization

### ISSUE THREAD

**Issue by rossmead** [semio-robotics/semio_ros#12]
The overall horizontal/vertical angle of "marker coverage" in the most recent deixis demo video was nice; however, as Edward mentioned, there seemed to be too many markers (targets) and it seemed distracting. Based on the Slack chat, it seems that a horizontal/vertical "density" of 10 or 15 degrees might be more appropriate (rather than 5 degrees in the deixis demo video).

**Comment by ekaszubski** [comment]
Fixing in #16

**Comment by ekaszubski** [comment]
Fixed in #16
