### ISSUE TITLE
Additional tracked person is visualized using multiple colors

### ISSUE THREAD

**Issue by rossmead** [semio-robotics/semio_ros#13]
The spheres/cylinders for an additional tracked person are multiple colors for that one person at the same time (i.e., some spheres/cylinders are one color, and some spheres/cylinders are another color).  Fortunately, the first person color is consistent.

**Comment by ekaszubski** [comment]
Please provide a screenshot/video of the issue

**Comment by rossmead** [comment]
<img width="960" alt="multi-color person" src="https://cloud.githubusercontent.com/assets/150612/18817303/2a3d13a8-8312-11e6-87b0-c88848c40b49.png">

Based on the screenshot, it appears that the "multi-color" effect _might_ be due to treating the second individual in the image as two tracked people; this is further supported by the fact that three arrows appear in the recognition output when there are only two people (something that we didn't notice live, as it was happening so quickly).  Hope this better illustrates the issue.

**Comment by ekaszubski** [comment]
Screenshot is of out-of-date code due to issue with test build 1 for #11 (now fixed). If the issue still exists, please post a new screenshot. Thanks!

**Comment by rossmead** [comment]
<img width="960" alt="more multi-color person tracking" src="https://cloud.githubusercontent.com/assets/150612/18822084/02533e68-8361-11e6-9266-6a7c5775dff9.png">

^ Updated screenshot, cross-posted from discussion in #11 .

**Comment by ekaszubski** [comment]
It looks like this screenshot applies to #14?

**Comment by rossmead** [comment]
The green crumpled skeleton is Braden taking the screenshot just as the issue popped up.  After that, the issue in #14 popped up (I'm actually working on a description+screenshot for you now).

The green skeleton on the left actually has both green and black limbs... o_O

**Comment by ekaszubski** [comment]
Fixing in #15

**Comment by ekaszubski** [comment]
Fixed in #15
