### ISSUE TITLE
Add BASE and WAIST to humanoids visualization

### ISSUE THREAD

**Issue by ekaszubski** [semio-robotics/semio_ros#17]
Need to determine how/where to specify ground plane. Ground plane transform `sensor -> ground plane` must be provided to `Humanoid::getJoint( BASE, transform ) <- VisualizationAdapter<Humanoid> [ <- VisualizationAdapter<Humanoids>, ... ] <- SemioVisualizationServerNode`.

Also need to explicitly request `BASE` and `WAIST` in `VisualizationAdapter<Humanoid>`; need to determine when/how to specify that this should happen.

**Comment by ekaszubski** [comment]
Proposal:
- Always try to draw `WAIST` frame
- Look up a `/sensor -> /world` transform; if it exists, try to draw `BASE`, using the transform data as the ground plane; otherwise do not draw `BASE`

**Comment by ekaszubski** [comment]
Implementing in #18

**Comment by rossmead** [comment]
Let's commit to there always being a world frame -- by default, the sensor is at the same pose as

The base pose then always has z=0 w.r.t. the world frame.

Alternatively (but least desirable in my opinion) is to simply set the base pose to being the same as either the waist or the torso (in order of preference).

In short, I'd like to treat base pose as being fundamental to the person so we can be assume that it's always there.

**Comment by ekaszubski** [comment]
Updated proposal:
- Always try to draw `WAIST` frame
- Look up a `/sensor -> /world` transform; if it exists, try to draw `BASE` using the transform data as the ground plane; otherwise try to draw `BASE` using the default zero transform

**Comment by rossmead** [comment]
^ Looks good. :-)

**Comment by ekaszubski** [comment]
Implemented in #18
