### ISSUE TITLE
Visualization: Attention visualization always uses HEAD

### ISSUE THREAD

**Issue by rossmead** [semio-robotics/semio_ros#26]
Use source with highest likelihood.

**Comment by ekaszubski** [comment]
Current algorithm:
- Use the ROOT top-n list to find the target with the highest total likelihood
- Use the HEAD as the starting point for the max likelihood indicator (arrow)

Proposed fix:
- Use the ROOT top-n list to find the target with the highest total likelihood
- Search through the other top-n lists; find the one with the highest likelihood of attending to the selected target; use the attention source associated with this top-n list as the starting point for the max likelihood indicator (arrow)

**Comment by ekaszubski** [comment]
Implementing in #28

**Comment by rossmead** [comment]
![inconsistent attention markers](https://cloud.githubusercontent.com/assets/150612/19048051/81b22220-8959-11e6-90a0-b3f1a0885805.png)

Really weird behavior -- the attention markers flicker with very different colors (including blue, purple, and magenta).

Also, the attention arrow (/closest/max) doesn't show up on the visualization list until *after* I cover my head so that the head position is not tracked; once it shows up on the visualization list, I don't ever actually see the arrow.

**Comment by ekaszubski** [comment]
Implemented in #28
